# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 485b325c2d82d7bf683156c4ce0b592549db8516cf8701b7d12bd4cbc82af06d174015377609de90b98d65b1783c907b404054ef9abc7dc8983a359774ae3a65

test:
  secret_key_base: b041b6e28142db5bd09b7421684286a359b5b1ccda7290000d5916bb462d5ea6d019ef25fbfb85253e252c29583c44313516b60f9a1d06e206c84ce8716ba8c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
